// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spiral: typeof import('./src/components/spiral.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopover: typeof import('vant/es')['Popover']
    VanSearch: typeof import('vant/es')['Search']
  }
}
